name: Auto Merge Approved PRs

on:
  pull_request_review:
    types:
      - submitted

# Add explicit permissions
permissions:
  contents: write
  pull-requests: write
  actions: read # Add permission to read Actions

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up GitHub CLI
        run: |
          gh --version || (
            echo "Installing GitHub CLI..."
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh -y
          )

      - name: Print debug information
        run: |
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "PR title: ${{ github.event.pull_request.title }}"
          echo "Review state: ${{ github.event.review.state }}"
          echo "Reviewer: ${{ github.event.review.user.login }}"

      - name: Check and wait for main branch CI
        id: check_main_ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if there are running workflows on the main branch
          WAIT_COUNT=0
          MAX_WAIT=6  # Wait up to 6 times, 5 minutes each, total 30 minutes

          while [ $WAIT_COUNT -lt $MAX_WAIT ]; do
            echo "Checking if there are running CI workflows on main branch..."
            RUNNING_WORKFLOWS=$(gh api repos/${{ github.repository }}/actions/runs --jq '.workflow_runs[] | select(.head_branch == "main" and .status == "in_progress") | .id' | wc -l)
            
            if [ $RUNNING_WORKFLOWS -gt 0 ]; then
              echo "Found $RUNNING_WORKFLOWS running workflow(s) on main branch, waiting 5 minutes before checking again..."
              WAIT_COUNT=$((WAIT_COUNT + 1))
              echo "This is wait attempt $WAIT_COUNT of maximum $MAX_WAIT"
              
              # If reached maximum wait count, abort the auto-merge
              if [ $WAIT_COUNT -eq $MAX_WAIT ]; then
                echo "Reached maximum wait time (30 minutes) and main branch CI is still running. Aborting auto-merge."
                echo "::set-output name=should_merge::false"
                exit 0
              fi
              
              sleep 300  # Wait 5 minutes
            else
              echo "No running CI on main branch, proceeding with auto-merge"
              echo "::set-output name=should_merge::true"
              break
            fi
          done

      - name: Auto-merge PR
        if: steps.check_main_ci.outputs.should_merge != 'false'
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "" # Allow merging PRs without specific labels
          MERGE_METHOD: "rebase" # Use rebase merge method
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FILTER_AUTHOR: "" # All authors allowed
          MERGE_DELETE_BRANCH: "true"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "1" # Require at least one approval
          LOG_LEVEL: "debug" # Add debug logs
