name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # 设置超时时间为10分钟

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Run tests sequentially
        run: npm test -- --runInBand # 确保测试按顺序运行而不是并行
      - name: Display test duration
        run: echo "Tests completed! CI pipeline should have run for about 5 minutes"
